import Link from "next/link";

const CONTACT_EMAIL = "info@medirealize.jp";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mt-8">
      <h2 className="mb-3 text-base font-bold text-honne-text">{title}</h2>
      <div className="space-y-2 text-sm leading-relaxed text-honne-secondary">{children}</div>
    </div>
  );
}

export default async function TermsPage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  const isEn = locale === "en";

  return (
    <div className="min-h-screen w-full bg-honne-bg font-sans text-honne-text antialiased">
      <div className="border-b border-honne-border-light bg-white">
        <div className="mx-auto flex max-w-2xl items-center justify-between px-5 py-3.5">
          <Link href={`/${locale}`} className="flex items-center gap-1.5 text-sm font-medium text-honne-secondary hover:text-honne-primary">
            <svg viewBox="0 0 20 20" className="h-4 w-4" fill="currentColor">
              <path fillRule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clipRule="evenodd" />
            </svg>
            {isEn ? "Back to honne." : "ほんね。に戻る"}
          </Link>
          <span className="text-sm font-bold text-honne-text">
            {isEn ? "Terms of Service" : "利用規約"}
          </span>
          <div className="w-16" />
        </div>
      </div>

      <div className="mx-auto max-w-2xl px-5 py-10">
        <div className="rounded-2xl border border-honne-border-light bg-white px-8 py-10 shadow-sm">
          {isEn ? (
            <>
              <h1 className="text-2xl font-bold text-honne-text">Terms of Service</h1>
              <p className="mt-2 text-sm text-honne-placeholder">Effective date: May 19, 2026</p>
              <p className="mt-6 text-sm leading-relaxed text-honne-secondary">
                These Terms of Service ("Terms") govern your use of honne. ("the App") provided by medirealize ("we" or "us"). Please read them carefully before using the App.
              </p>
              <Section title="Article 1 — Purpose of the Service">
                <p>The App is a communication support tool that helps users put unspoken feelings into words.</p>
                <p>The App is <strong>not</strong>:</p>
                <ul className="ml-4 list-disc space-y-1">
                  <li>A service providing medical diagnosis or medical advice</li>
                  <li>A psychotherapy or counseling service</li>
                  <li>A legal consultation service</li>
                </ul>
                <p>If you have serious health or mental concerns, please consult a qualified medical professional or support service.</p>
              </Section>
              <Section title="Article 2 — Prohibited Conduct">
                <p>Users must not engage in any of the following:</p>
                <ul className="ml-4 list-disc space-y-1">
                  <li>Any act that violates laws or public order and morals</li>
                  <li>Any act that infringes on the rights of us or third parties</li>
                  <li>Unauthorized access to or excessive burden on the App</li>
                  <li>Entering content that defames, discriminates against, or harasses others</li>
                  <li>Unauthorized commercial use or reproduction of the App's content</li>
                </ul>
              </Section>
              <Section title="Article 3 — Nature of AI and Disclaimer">
                <p>Content generated by the App is <strong>reference information</strong> based on AI and personality statistics. Please note the following:</p>
                <ul className="ml-4 list-disc space-y-1">
                  <li>Generated content may not always be accurate or complete, and results vary by individual</li>
                  <li>Do not use it as grounds for medical, legal, or therapeutic decisions</li>
                  <li>If an AI response feels off, trust your own judgment</li>
                </ul>
              </Section>
              <Section title="Article 4 — Premium Plan and Refunds">
                <p>The Premium plan is a monthly subscription service.</p>
                <ul className="ml-4 list-disc space-y-1">
                  <li>Payments are processed through Stripe, Inc.</li>
                  <li>To cancel, please do so from your account settings before the next renewal date</li>
                  <li>Due to the nature of digital services, refunds are not available in principle</li>
                  <li>This does not apply where refunds are required by applicable law</li>
                </ul>
              </Section>
              <Section title="Article 5 — Changes and Termination of Service">
                <p>We may modify, suspend, or terminate the App without prior notice. We are not liable for any damages to users resulting from such actions.</p>
              </Section>
              <Section title="Article 6 — Governing Law and Jurisdiction">
                <p>These Terms are governed by the laws of Japan. In the event of a dispute, the Miyazaki District Court shall have exclusive jurisdiction as the court of first instance.</p>
              </Section>
              <Section title="Contact">
                <p>For inquiries regarding these Terms, please contact us:</p>
                <p>Email: <a href={`mailto:${CONTACT_EMAIL}`} className="text-honne-primary underline">{CONTACT_EMAIL}</a></p>
              </Section>
            </>
          ) : (
            <>
              <h1 className="text-2xl font-bold text-honne-text">利用規約</h1>
              <p className="mt-2 text-sm text-honne-placeholder">制定日：2026年5月19日</p>
              <p className="mt-6 text-sm leading-relaxed text-honne-secondary">
                本規約は、medirealize（以下「当社」）が提供するほんね。（以下「本アプリ」）の利用条件を定めるものです。本アプリをご利用いただく前に、必ずお読みください。
              </p>
              <Section title="第1条（サービスの目的）">
                <p>本アプリは、ユーザーが抱える「言葉にできない気持ち」を言語化することを支援するコミュニケーションサポートツールです。</p>
                <p>本アプリは以下のものでは<strong>ありません</strong>。</p>
                <ul className="ml-4 list-disc space-y-1">
                  <li>医療診断・医学的助言を提供するサービス</li>
                  <li>心理療法・カウンセリングサービス</li>
                  <li>法律相談サービス</li>
                </ul>
                <p>体調・精神面に深刻な不安がある場合は、必ず専門の医療機関・相談窓口をご利用ください。</p>
              </Section>
              <Section title="第2条（禁止事項）">
                <p>ユーザーは以下の行為を行ってはなりません。</p>
                <ul className="ml-4 list-disc space-y-1">
                  <li>法令または公序良俗に違反する行為</li>
                  <li>当社または第三者の権利を侵害する行為</li>
                  <li>本アプリへの不正アクセス・過剰な負荷をかける行為</li>
                  <li>他者を誹謗中傷・差別する内容の入力</li>
                  <li>商業目的での無断利用・転載</li>
                </ul>
              </Section>
              <Section title="第3条（AIの性質と免責）">
                <p>本アプリが生成する内容はAIと性格統計学に基づく<strong>参考情報</strong>であり、以下の点をご理解のうえご利用ください。</p>
                <ul className="ml-4 list-disc space-y-1">
                  <li>生成内容は必ずしも正確・完全ではなく、個人差があります</li>
                  <li>医学的・法的・心理療法的な判断の根拠としないでください</li>
                  <li>AIの回答に違和感を感じた場合は、ご自身の判断を優先してください</li>
                </ul>
              </Section>
              <Section title="第4条（プレミアムプランと返金）">
                <p>プレミアムプランは月額制のサブスクリプションです。</p>
                <ul className="ml-4 list-disc space-y-1">
                  <li>お支払いはStripe社を通じて処理されます</li>
                  <li>解約は次回更新日の前日までにアカウント設定からお手続きください</li>
                  <li>デジタルサービスの性質上、原則として返金はお受けできません</li>
                  <li>法令により返金が必要な場合はこの限りではありません</li>
                </ul>
              </Section>
              <Section title="第5条（サービスの変更・終了）">
                <p>当社は事前の通知なく、本アプリの内容を変更・一時停止・終了することがあります。これによりユーザーに生じた損害について、当社は責任を負いません。</p>
              </Section>
              <Section title="第6条（準拠法・管轄）">
                <p>本規約は日本法を準拠法とし、紛争が生じた場合は宮崎地方裁判所を第一審の専属的合意管轄裁判所とします。</p>
              </Section>
              <Section title="お問い合わせ">
                <p>本規約に関するお問い合わせは以下までご連絡ください。</p>
                <p>メール：<a href={`mailto:${CONTACT_EMAIL}`} className="text-honne-primary underline">{CONTACT_EMAIL}</a></p>
              </Section>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
